/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    HomeBottom: typeof import('./src/components/widgets/topBox/HomeBottom.vue')['default']
    ItemFile: typeof import('./src/components/widgets/mainbox/operaview/itemFile.vue')['default']
    MainBox: typeof import('./src/components/MainBox.vue')['default']
    MenuBottom: typeof import('./src/components/widgets/topBox/MenuBottom.vue')['default']
    PathBox: typeof import('./src/components/widgets/mainbox/operaview/pathBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBottom: typeof import('./src/components/widgets/topBox/SearchBottom.vue')['default']
    SearchBox: typeof import('./src/components/widgets/mainbox/operaview/searchBox.vue')['default']
    TopBox: typeof import('./src/components/TopBox.vue')['default']
    UserInfo: typeof import('./src/components/widgets/topBox/UserInfo.vue')['default']
    WinLabel: typeof import('./src/components/widgets/mainbox/operaview/winLabel.vue')['default']
  }
}
